# This container is specific to the application.
# It contains configuration and data for other containers.
data:
    build: ./docker
    volumes:
        - /home/greg/dev/docker-base-images/sample_symfony_app:/srv
        - /home/greg/dev/docker-base-images/sample_symfony_app/docker/conf/nginx_vhost.conf:/etc/nginx/sites-enabled/my_app.conf

webserver:
    build: ./docker/docker-images/nginx
    ports:
        - '80:80'
    volumes_from:
        - data
    links:
        - appserver

appserver:
    build: ./docker/docker-images/php
    ports:
        - '9000:9000'
    volumes_from:
        - data
    links:
        - database
        - memorycache
        - elasticsearch
        - mailer

database:
    build: ./docker/docker-images/postgres
    ports:
        - '5432:5432'
    volumes_from:
        - data
    environment:
        POSTGRES_DB: sample_app
        POSTGRES_USER: sample_app
        POSTGRES_PASSWORD: sample_app

mailer:
    build: ./docker/docker-images/mailcatcher
    ports:
        - '1080:1080'
        - '1025:1025'

memorycache:
    build: ./docker/docker-images/memcached
    ports:
        - '11211:11211'

elasticsearch:
    build: ./docker/docker-images/elasticsearch
    volumes_from:
        - data
    ports:
        - "9200:9200"
        - "9300:9300"
